// node bench/mdreport.js  -- emit markdown tables for the guide.
'use strict';
const fs = require('fs'), path = require('path');
const OUT = path.join(__dirname, 'out');
const has = t => fs.existsSync(path.join(OUT, t + '.json'));
const load = t => JSON.parse(fs.readFileSync(path.join(OUT, t + '.json'), 'utf8'));
const ENGINES = ['edge', 'firefox', 'firefox-nonaccel'].filter(has);
const NICE = { edge: 'Chromium 152', firefox: 'Firefox 155', 'firefox-nonaccel': 'Firefox 155, `gfx.canvas.accelerated=false`' };

function sceneTable(tag) {
  const j = load(tag), lines = [];
  for (const s of j.scenes || []) {
    lines.push('');
    lines.push('**' + s.name + '** — ' + s.nVis + ' visible triangles; geometry stage (transform + cull + shade + radix sort) ' + s.sceneMs + ' ms');
    lines.push('');
    lines.push('| strategy | fills | subpaths | verts | record ms | raster ms | RMSE vs 4× truth | >48 % |');
    lines.push('|---|--:|--:|--:|--:|--:|--:|--:|');
    for (const r of s.rows) {
      const t = r.truth || {};
      lines.push('| ' + r.case + ' | ' + r.fills + ' | ' + r.subpaths + ' | ' + r.verts + ' | ' +
        r.recMs + ' | ' + r.rasterMs + ' | ' + t.rmse + ' | ' + t.gt48Pct + ' |');
    }
  }
  return lines.join('\n');
}

function microTable() {
  const cols = ENGINES.filter(has);
  const maps = cols.map(t => { const m = new Map(); for (const x of load(t).micro || []) m.set(x.name, x); return m; });
  const names = [];
  for (const m of maps) for (const k of m.keys()) if (!names.includes(k)) names.push(k);
  const lines = [];
  lines.push('| case | ' + cols.map(c => NICE[c] + ' record / raster').join(' | ') + ' |');
  lines.push('|---|' + cols.map(() => '--:').join('|') + '|');
  for (const n of names) {
    if (n === 'sustained-only') continue;
    const cells = maps.map(m => {
      const x = m.get(n);
      if (!x) return '—';
      return x.rasterMs === null || x.rasterMs === undefined ? String(x.recMs) : x.recMs + ' / ' + x.rasterMs;
    });
    lines.push('| `' + n.replace(/\s+/g, ' ').trim() + '` | ' + cells.join(' | ') + ' |');
  }
  return lines.join('\n');
}

function sustainedTable() {
  const tags = ENGINES.map(e => e + '-sus').filter(has);
  if (!tags.length) return '(sustained run not present)';
  const lines = [];
  for (const t of tags) {
    const j = load(t);
    for (const s of j.scenes || []) {
      lines.push('');
      lines.push('**' + (NICE[t.replace('-sus', '')] || t) + ' — ' + s.name + '** (' + s.nVis + ' visible)');
      lines.push('');
      lines.push('| strategy | fills | verts | reps/frame | frame ms | per-draw ms | of which CPU | not visible to `performance.now()` |');
      lines.push('|---|--:|--:|--:|--:|--:|--:|--:|');
      for (const r of s.rows)
        lines.push('| ' + r.case + ' | ' + r.fills + ' | ' + r.verts + ' | ' + r.reps + ' | ' +
          r.frameMs + ' | **' + r.perDrawMs + '** | ' + r.cpuPerDrawMs + ' | ' + r.gpuShareMs + ' |');
    }
  }
  return lines.join('\n');
}

console.log('<!-- generated by bench/mdreport.js -->');
for (const e of ENGINES) {
  console.log('\n\n### ' + NICE[e] + '\n');
  console.log('`' + load(e).env.ua + '`');
  console.log(sceneTable(e));
}
console.log('\n\n### Sustained, GPU-inclusive\n');
console.log(sustainedTable());
console.log('\n\n### Micro-benchmarks (1024×1024, 8000 triangles unless noted)\n');
console.log(microTable());
